angular.module(
  'client',
  [
    'ngSanitize',
    'ui.router',
    'ui.select',
    'templates',
    'ngResource',
    'ngAnimate',
    'angular-growl',
    'ngEnter',
    'DatePicker',
    'ActiveSelect',
    'NgActive',
    'Sidebar',
    'Logs',
    'ToggableField',
    'Header',
    'PageHeader',
    'ProductList',
    'ProductModal',
    'ProductStatus',
    'satellizer'
    'CategoryList',
    'CategoryModal',
    'Reminders',
    'GrocerySearch',
    'GroceryList',
    'GroceryForms',
    'GrocerySummary',
    'ngCsv'
  ]
)
